apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: XCore
metadata:
  name: space-base
spec:
  parameters:
    providerConfigName: aws-spaces-hostcluster
    spaces:
      version: 1.3.0
      dns:
        spacesRouterDomain: platform-ref-upbound-spaces.upboundrocks.cloud
      clusterType: eks
      account: platform-ref
      pullSecretRef:
        name: upbound-provider-helm-pull
        namespace: upbound-system
