apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-ref-upbound-spaces
  annotations:
    meta.crossplane.io/maintainer: The platform-ref-upbound-spaces Configuration
    meta.crossplane.io/source: github.com/upbound/platform-ref-upbound-spaces
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This platform-ref-upbound-spaces configuration offers upbound space installation.
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      # renovate: datasource=github-releases depName=upbound/configuration-aws-network
      version: "v0.11.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks
      # renovate: datasource=github-releases depName=upbound/configuration-aws-eks
      version: "v0.9.0"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-network
      # renovate: datasource=github-releases depName=upbound/configuration-azure-network
      version: "v0.7.0"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-aks
      # renovate: datasource=github-releases depName=upbound/configuration-azure-aks
      version: "v0.6.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gcp-network
      # renovate: datasource=github-releases depName=upbound/configuration-gcp-network
      version: "v0.3.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gcp-gke
      # renovate: datasource=github-releases depName=upbound/configuration-gcp-gke
      version: "v0.3.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gitops-argocd
      # renovate: datasource=github-releases depName=upbound/configuration-gitops-argocd
      version: "v0.8.0"
    - function: xpkg.upbound.io/upboundcare/function-conditional-patch-and-transform
      version: "v0.4.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.3.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      # renovate: datasource=github-releases depName=crossplane-contrib/function-auto-ready
      version: "v0.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      # renovate: datasource=github-releases depName=crossplane-contrib/function-go-templating
      version: "v0.4.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-sequencer
      # renovate: datasource=github-releases depName=crossplane-contrib/function-sequencer
      version: "v0.1.0"
