apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: azure-spaces-hostcluster
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: azure
    id: azure-spaces-hostcluster
    region: westus
    version: "1.27.3"
    nodes:
      count: 1
      instanceType: Standard_B2s
  writeConnectionSecretToRef:
    name: azure-spaces-hostcluster-kubeconfig
