apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: gcp-spaces-hostcluster
  namespace: default
  annotations:
    render.crossplane.io/composition-path: apis/cluster/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: gcp
    id: gcp-spaces-hostcluster
    region: us-west2
    version: latest
    nodes:
      count: 3
      instanceType: n1-standard-4
  writeConnectionSecretToRef:
    name: gcp-spaces-hostcluster-kubeconfig
