apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: XCore
metadata:
  name: space-base
  annotations:
    render.crossplane.io/composition-path: apis/space-core/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
spec:
  parameters:
    providerConfigName: aws-spaces-hostcluster
    spaces:
      version: 1.3.0
      dns:
        spacesRouterDomain: platform-ref-upbound-spaces.${data.route53ZoneName}
      clusterType: eks
      account: platform-ref
      pullSecretRef:
        name: upbound-provider-helm-pull
        namespace: upbound-system
