apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: XInit
metadata:
  name: space-base
  annotations:
    render.crossplane.io/composition-path: apis/space-init/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
spec:
  parameters:
    providerConfigName: aws-spaces-hostcluster
    operators:
      certmanager:
        enabled: true
        version: v1.14.3
      ingressnginx:
        enabled: true
        version: "4.9.1"
      externaldns:
        aws:
          enabled: true
          route53ZoneId: ${data.route53ZoneId}
          route53ZoneName: ${data.route53ZoneName}
        version: "6.34.2"
      crossplane:
        enabled: true
        version: v1.15.2-up.1
        providers:
          - name: provider-helm
            package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.17.0
            enabled: true
            localRbac: true
          - name: provider-kubernetes
            package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.1
            enabled: true
            localRbac: true
