apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: Space
metadata:
  name: hostcluster-aks
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: azure
    id: hostcluster-aks
    region: westus
    version: "1.28"
    nodes:
      count: 1
      instanceType: standard_d8s_v3
    operators:
      argocd:
        enabled: true
        ingressUrl: argocd-platform-ref-upbound-spaces.${data.route53ZoneName}
        git:
          url: https://github.com/upbound/platform-ref-upbound-spaces.git
          path: gitops
          ref:
            name: HEAD
        resourceExclusions: |
          - kinds:
            - ProviderConfigUsage
            apiGroups:
            - "*"
          - kinds:
            - "Nodes"
            apiGroups:
            - "*"
            clusters:
            - "*/controlplane-*"
        resourceInclusions: |
          - apiGroups:
            - "*"
            kinds:
            - Provider
            - Function
            - Configuration
            - CompositeResourceDefinition
            - Composition
            - Application
            clusters:
            - "*/controlplane-*"
    spaces:
      dns:
        spacesRouterDomain: platform-ref-upbound-spaces-aks.${data.route53ZoneName}
      account: platform-ref
  writeConnectionSecretToRef:
    name: hostcluster-aks-kubeconfig
