apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: Space
metadata:
  name: hostcluster-aks
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: azure
    id: hostcluster-aks
    region: westus
    version: "1.28"
    nodes:
      count: 1
      instanceType: standard_d8s_v3
    operators:
      crossplane:
        providers:
          - name: provider-helm
            package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.17.0
            localRbac: true
          - name: provider-kubernetes
            package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.1
            localRbac: true
    spaces:
      dns:
        spacesRouterDomain: platform-ref-upbound-spaces-aks.upboundrocks.cloud
      clusterType: aks
      account: platform-ref
  writeConnectionSecretToRef:
    name: hostcluster-aks-kubeconfig
