apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: Space
metadata:
  name: hostcluster-gcp
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: gcp
    id: hostcluster-gcp
    region: us-west2
    version: latest
    nodes:
      count: 3
      instanceType: e2-standard-4
    operators:
      externaldns:
        # To leverage external-dns for managing the spaces.dns.spacesRouterDomain zone entry,
        # substitute the placeholder values with your actual Managed Zone Name and GCP DNS Project Name.
        name: ${data.gcpZoneName}
        id: ${data.gcpDNSProject}
      argocd:
        enabled: true
        ingressUrl: argocd-platform-ref-upbound-spaces.${data.gcpZoneName}
        git:
          url: https://github.com/upbound/platform-ref-upbound-spaces.git
          path: gitops
          ref:
            name: HEAD
        resourceExclusions: |
          - kinds:
            - ProviderConfigUsage
            apiGroups:
            - "*"
          - kinds:
            - "Nodes"
            apiGroups:
            - "*"
            clusters:
            - "*/controlplane-*"
        resourceInclusions: |
          - apiGroups:
            - "*"
            kinds:
            - Provider
            - Function
            - Configuration
            - CompositeResourceDefinition
            - Composition
            - Application
            clusters:
            - "*/controlplane-*"
    spaces:
      dns:
        spacesRouterDomain: platform-ref-upbound-spaces-gke.${data.gcpZoneName}
      account: platform-ref
  writeConnectionSecretToRef:
    name: hostcluster-gcp-kubeconfig
