apiVersion: spaces.platformref.upbound.io/v1alpha1
kind: Space
metadata:
  name: hostcluster-gcp
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: gcp
    id: hostcluster-gcp
    region: us-west2
    version: latest
    nodes:
      count: 3
      instanceType: e2-standard-4
    operators:
      certmanager:
        gcp:
          enabled: true
          zoneName: ${data.gcpZoneName}
          dnsProject: ${data.gcpDNSProject}
      externaldns:
        gcp:
          enabled: true
          # To leverage external-dns for managing the spaces.dns.spacesRouterDomain zone entry,
          # substitute the placeholder values with your actual Managed Zone Name and GCP DNS Project Name.
          zoneName: ${data.gcpZoneName}
          dnsProject: ${data.gcpDNSProject}
      crossplane:
        providers:
          - name: provider-helm
            package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.17.0
            localRbac: true
          - name: provider-kubernetes
            package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.1
            localRbac: true
      argocd:
        enabled: true
        ingressUrl: argocd-platform-ref-upbound-spaces.${data.gcpZoneName}
        git:
          url: https://github.com/upbound/platform-ref-upbound-spaces.git
          path: gitops
          ref:
            name: HEAD
        resourceExclusions: |
          - kinds:
            - ProviderConfigUsage
            apiGroups:
            - "*"
          - kinds:
            - "Nodes"
            apiGroups:
            - "*"
            clusters:
            - "*/controlplane-*"
        resourceInclusions: |
          - apiGroups:
            - "*"
            kinds:
            - Provider
            - Function
            - Configuration
            - CompositeResourceDefinition
            - Composition
            - Application
            clusters:
            - "*/controlplane-*"
    spaces:
      dns:
        spacesRouterDomain: platform-ref-upbound-spaces-gke.${data.gcpZoneName}
      clusterType: gke
      account: platform-ref
  writeConnectionSecretToRef:
    name: hostcluster-gcp-kubeconfig
