apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xspaces.spaces.platformref.upbound.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: spaces.platformref.upbound.io
  names:
    kind: XSpace
    plural: xspaces
  claimNames:
    kind: Space
    plural: spaces
  connectionSecretKeys:
    - kubeconfig
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .spec.parameters.cloud
          name: CLOUD
          type: string
        - jsonPath: .spec.compositionRevisionRef.name
          name: COMPOSITION REVISION
          type: string
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Cluster configuration parameters.
                  properties:
                    cloud:
                      description: Cloud is the cloud provider you'd like your cluster resources to be created in.
                      type: string
                      enum:
                        - aws
                        - gcp
                        - azure
                    id:
                      type: string
                      description: ID of this Cluster that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    iam:
                      type: object
                      description: IAM configuration to connect as ClusterAdmin.
                      properties:
                        roleArn:
                          description: The IAM Role ARN to connect as ClusterAdmin.
                          type: string
                        userArn:
                          description: The IAM User ARN to connect as ClusterAdmin.
                          type: string
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: "Delete"
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: "default"
                    version:
                      type: string
                      description: Kubernetes version of the Cluster
                    nodes:
                      type: object
                      description: Cluster node configuration parameters.
                      properties:
                        count:
                          type: integer
                          description: Desired node count, from 1 to 100.
                        instanceType:
                          type: string
                          description: instance types associated with the Node Group.
                      required:
                        - count
                        - instanceType
                    operators:
                      type: object
                      description: "Defines the operators to be deployed with their enabled status and versions."
                      default:
                        certmanager:
                          enabled: true
                        ingressnginx:
                          enabled: true
                      properties:
                        argocd:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: "Indicates if argocd is enabled."
                              default: false
                            version:
                              type: string
                              description: "Specifies the version of argocd helm-chart to use."
                            ingressUrl:
                              type: string
                              description: set ingressUrl for argocd server
                            resourceExclusions:
                              type: string
                              description: configure the list of exclude resources
                            resourceInclusions:
                              type: string
                              description: configure the list of included resources
                            git:
                              type: object
                              properties:
                                url:
                                  description: URL specifies the Git repository URL, it can be an HTTP/S address.
                                  pattern: ^(http|https)://.*\.git$
                                  type: string
                                path:
                                  type: string
                                ref:
                                  description: Reference specifies the Git reference to resolve and
                                    monitor for changes.
                                  type: object
                                  properties:
                                    name:
                                      description: "Name of the reference to check out"
                                      type: string
                              required:
                                - url
                                - ref
                        certmanager:
                          type: object
                          default:
                            enabled: true
                          properties:
                            enabled:
                              type: boolean
                              description: "Indicates if cert-manager is enabled."
                              default: true
                            version:
                              type: string
                              description: "Specifies the version of cert-manager to use."
                          required:
                            - enabled
                        ingressnginx:
                          type: object
                          default:
                            enabled: true
                          properties:
                            enabled:
                              type: boolean
                              description: "Indicates if ingress-nginx is enabled."
                              default: true
                            version:
                              type: string
                              description: "Specifies the version of ingress-nginx to use."
                          required:
                            - enabled
                        externaldns:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: "Indicates if external-dns is enabled."
                              default: true
                            id:
                              type: string
                            name:
                              type: string
                            version:
                              type: string
                              description: "Specifies the version of external-dns to use."
                              default: "6.34.2"
                          required:
                            - version
                            - enabled
                    spaces:
                      type: object
                      description: "Defines the configuration for spaces."
                      properties:
                        version:
                          type: string
                          description: "The version of the space configuration."
                        dns:
                          type: object
                          properties:
                            spacesRouterDomain:
                              type: string
                              description: "The domain for the spaces router."
                          required:
                            - spacesRouterDomain
                        account:
                          type: string
                          description: "The account identifier for the space."
                        pullSecretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              description: "The name of the pull secret to use."
                            namespace:
                              type: string
                              description: "The namespace of the pull secret."
                          required:
                            - name
                            - namespace
                      required:
                        - dns
                        - account
                  required:
                    - cloud
                    - deletionPolicy
                    - id
                    - nodes
                    - operators
                    - providerConfigName
                    - region
                    - spaces
              required:
                - parameters
            status:
              type: object
              properties:
                subnetIds:
                  type: array
                  items:
                    type: string
