apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xinit.spaces.platformref.upbound.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: spaces.platformref.upbound.io
  names:
    kind: XInit
    plural: xinit
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .spec.parameters.operators.crossplane.version
          name: CROSSPLANE
          type: string
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    providerConfigName:
                      type: string
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    operators:
                      type: object
                      description: "Defines the operators to be deployed with their enabled status and versions."
                      properties:
                        certmanager:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: "Indicates if cert-manager is enabled."
                            version:
                              type: string
                              description: "Specifies the version of cert-manager to use."
                        ingressnginx:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: "Indicates if ingress-nginx is enabled."
                            version:
                              type: string
                              description: "Specifies the version of ingress-nginx to use."
                        externaldns:
                          type: object
                          properties:
                            aws:
                              type: object
                              properties:
                                enabled:
                                  type: boolean
                                  description: "Indicates if AWS external-dns is enabled."
                                route53ZoneId:
                                  type: string
                                  description: "The Route53 zone ID for external-dns to manage."
                                route53ZoneName:
                                  type: string
                                  description: "The Route53 zone name for external-dns to manage."
                            version:
                              type: string
                              description: "Specifies the version of external-dns to use."
                        crossplane:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: "Indicates if Crossplane is enabled."
                            version:
                              type: string
                              description: "Specifies the version of Crossplane to use."
                            providers:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                    description: "The name of the Crossplane provider."
                                  package:
                                    type: string
                                    description: "The package of the Crossplane provider."
                                  enabled:
                                    type: boolean
                                    description: "Indicates if the Crossplane provider is enabled."
                                  localRbac:
                                    type: boolean
                                    description: "Indicates if local RBAC is enabled for the provider."
            status:
              type: object
              properties:
                status:
                  description: Freeform field containing status information
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
